# GoReleaser 設定
# 参考: https://goreleaser.com/customization/

version: 2

project_name: twins-diff

builds:
  - id: twins-diff
    main: ./cmd/twins-diff
    binary: twins-diff
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}

archives:
  - id: default
    format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"

brews:
  - name: twins-diff
    repository:
      owner: the-red
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/the-red/twins-diff"
    description: "Web-based tool for comparing two directory trees"
    license: "MIT"
    install: |
      bin.install "twins-diff"
    test: |
      system "#{bin}/twins-diff", "-h"
